version: "3.9"
services:
  student-statistics-process:
    image: 5aleda4rf/student-statistics-process
    volumes:
      - ./app/data/batch:/app/data/batch
    ports:
      - "80:80"
    stdin_open: true
    tty: true
  registeration-process:
    image: 5aleda4rf/registeration-process
    volumes:
      - ./app/data/batch:/app/data/batch
    ports:
      - "81:81"
    stdin_open: true
    tty: true


volumes:
  ./app/data/batch:
