version: "3.9"
services:
  student-statistics-process:
    image: 5aleda4rf/student-statistics-process
    ports:
      - "80:80"
    stdin_open: true
    tty: true
  registeration-process:
    image: 5aleda4rf/registeration-process
    ports:
      - "81:81"
    stdin_open: true
    tty: true


