name: Build and Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        run: |
          docker buildx bake -f ./docker-compose.yml default --push

      - name: Run docker compose (Test)
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: ./docker-compose.yml
          services: student-statistics-process registeration-process
      - name: Run Test in registeration-process service
        run: |
          docker exec -it students_registration_system-registeration-process-1 bash
          java Main   
          
      - name: Run Test in student-statistics-process service
        run: |
          docker exec -it students_registration_system-student-statistics-process-1 bash
          java Main
