name: Build and Test
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run docker-compose
        run: |
          docker-compose up -d

      - name: Run Test in registeration-process service
        run: |
          docker exec -it students_registration_system_registeration-process_1 -t bash
          java Main   
          
      - name: Run Test in student-statistics-process service
        run: |
          docker exec -it students_registration_system_student-statistics-process_1 -t bash
          java Main
